### ISSUE TITLE
Add bios to project

### ISSUE THREAD

**Issue by hubyeti** [kevinjaquith/github-for-developers-7#3]
We should all create great bios in this project. Make sure your bio includes:

```
     - [ ] Your name
     - [ ] Where you are from
     - [ ] A favorite food
     - [ ] A hobby
```

**Comment by kevinjaquith** [comment]
My name is Kevin jaquith and I live in Boston. I enjoy running when the weather is nice. If you were to ask me what my favorite food is, I'd promptly reply "chicken salad." I love working in Boston and getting to walk through Boston Common every day on my way to work.
